name: Build and Test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build
        run: |
          chmod +x gradlew && chmod +x *
          ./gradlew build
          echo ========================================
          ls ${{ github.workspace }}/app/build/outputs/
          echo ========================================
          ls ${{ github.workspace }}/app/build/outputs/apk/release/
          echo ========================================

      # - name: arm64
        # uses: actions/upload-artifact@v4
        # with:
          # name: Arm64
          # path: ${{ github.workspace }}/app/build/outputs/apk/release/*arm64-v8a.apk

      # - name: armeabi-v7a
        # uses: actions/upload-artifact@v4
        # with:
          # name: Armeabi-v7a
          # path: ${{ github.workspace }}/app/build/outputs/apk/release/*armeabi-v7a.apk
          
